name: ResInsight Build

on: [push]

jobs:
  ResInsight-x64:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: true
      
      - name: Run vcpkg
        uses: lukka/run-vcpkg@dev
        id: runvcpkg
        with:
          # Member field access: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/contexts-and-expression-syntax-for-github-actions
          vcpkgArguments: 'install grpc --triplet x64-windows'
          vcpkgDirectory: ${{ github.workspace }}/../b/vcpkg
          vcpkgGitCommitId: 8b4a607c328d100ac9892e2cbcfb9a4b0cf44c10
      
      - name: Install Qt
        uses: ouuan/install-qt-action@v2.3.1
        with:
          version: 5.9.1
          host: windows
          target: desktop
          arch: win64_msvc2017_64
          modules: qtscript 
      - name: Build ResInsight-x64
        env:
          CMAKE_PREFIX_PATH: ${{ runner.workspace }}\Qt\5.9.1\msvc2017_64
        run: |
          mkdir cmakebuild
          cd cmakebuild
          cmake .. -DRESINSIGHT_ENABLE_PRECOMPILED_HEADERS=true -DRESINSIGHT_ENABLE_UNITY_BUILD=true
          cmake --build . --config Release --target PACKAGE
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: ResInsight
          path: ${{ runner.workspace }}/ResInsight/cmakebuild/packages

  